#!/usr/bin/env sh

set -euo pipefail

export DIR="$(cd $(dirname ${0}); pwd)"

LOGGING_PROPS_FILE_NAME="logging.properties"
LOGGING_PROPS_FILE="${LOGGING_PROPS_FILE:-${HOME}/.okta"/${LOGGING_PROPS_FILE_NAME}"}"

# Copy the input array into a named variable
ARGS=("${@}")

# 1. Expand the array so each argument gets passed on
# Just using $@ to pass to the next function means spaces
# will split a single argument. Using $@ here results in "${("$@")[@]}: bad substitution"
"${DIR}/java" -Djava.util.logging.config.file="${LOGGING_PROPS_FILE}" \
  -classpath "${DIR}/okta-aws-cli-assume-role.jar" \
  com.okta.tools.WithOkta \
  "${ARGS[@]:-true}"
