#!/usr/bin/env sh
set -e

export DIR="$(cd $(dirname ${BASH_SOURCE}); pwd)"

LOGGING_PROPS_FILE_NAME="logging.properties"
OKTA_DIR="${HOME}/.okta"
LOGGING_PROPS_FILE="${OKTA_DIR}/${LOGGING_PROPS_FILE_NAME}"

if [ ! -f "${LOGGING_PROPS_FILE}" ]; then
  mkdir -p "${OKTA_DIR}"
  cat "${DIR}/${LOGGING_PROPS_FILE_NAME}" > "${LOGGING_PROPS_FILE}"
fi

# Copy the input array into a named variable
ARGS=("$@")

# 1. Expand the array so each argument gets passed on
# Just using $@ to pass to the next function means spaces
# will split a single argument. Using $@ here results in "${("$@")[@]}: bad substitution"
"${DIR}/java" -Djava.util.logging.config.file="${LOGGING_PROPS_FILE}" \
  -classpath "${DIR}/okta-aws-cli-assume-role.jar" \
  com.okta.tools.WithOkta \
  "${ARGS[@]}"
