name: PR Build and Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '19'
      - name: Cache tmp
        id: cacheTmp
        uses: actions/cache@v3
        with:
          path: tmp
          key: ${{ runner.os }}
      - run: ./prepareReleases
      - name: Automatic Releases
        id: release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Development Build"
          automatic_release_tag: 'latest'
          files: releases/*

