name: PR Build and Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '19'
      - name: Cache tmp
        id: cacheTmp
        uses: actions/cache@v3
        with:
          path: tmp
          key: ${{ runner.os }}
      - run: ./prepareReleases
      - name: Bump version and push tag
        id: version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRERELEASE: true
      - name: release
        uses: softprops/action-gh-release@v1
        id: createRelease
        with:
          draft: false
          prerelease: true
          tag_name: ${{ steps.version.outputs.new_tag }}
          release_name: ${{ steps.version.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Assets
        id: uploadAssets
        run: ./uploadReleaseAssets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOAD_URL: ${{ steps.createRelease.outputs.upload_url }}

