name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          distribution: 'zulu'
          java-version: '19'
      - run: ./prepareReleases
